//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insaat_MVC_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public int Id { get; set; }
        public string SenderEmail { get; set; }
        public string SenderPassword { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> EnableSsl { get; set; }
        public string ReceiverMail { get; set; }
    }
}
