//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insaat_MVC_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pages()
        {
            this.PageImage = new HashSet<PageImage>();
        }
    
        public int Id { get; set; }
        public string PageName { get; set; }
        public string ImageURL { get; set; }
        public string ThumbURL { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKey { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> PageCategoryId { get; set; }
        public Nullable<int> LangId { get; set; }
    
        public virtual Lang Lang { get; set; }
        public virtual PageCategory PageCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageImage> PageImage { get; set; }
    }
}
