//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insaat_MVC_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageCategory()
        {
            this.Pages = new HashSet<Pages>();
        }
    
        public int Id { get; set; }
        public string PageCategoryName { get; set; }
        public string ImageURL { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKey { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> LangId { get; set; }
    
        public virtual Lang Lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pages> Pages { get; set; }
    }
}
