//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insaat_MVC_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Id { get; set; }
        public string SliderTitle { get; set; }
        public string ImageURL { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> LangId { get; set; }
    
        public virtual Lang Lang { get; set; }
    }
}
